# Generated by Django 5.2.1 on 2025-05-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('directors', models.TextField(null=True)),
                ('cast', models.TextField(null=True)),
                ('plot', models.TextField(null=True)),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
